### ISSUE TITLE
Ability to specify OS platform

### ISSUE THREAD

**Issue by djemalmohamed** [sgraham785/flywaydb-cli#10]
Hello,

When working (dev) on mac os and then publish the project to a linux docker container, the flyway cli command will not work because of the jre incompatibility between different OSs.

Is there any possibility to specify/force os type on installing the package please?

Thanks in advance.

**Comment by sgraham785** [comment]
the installer looks to install the JRE for the specific OS already. 
you should either be reinstalling the packages on the docker environment or developing using the docker environment. 
it's poor practice to install everything on macOS and expect everything to work the same way on linux.
