### ISSUE TITLE
Ability to specify flyway version?

### ISSUE THREAD

**Issue by juanjoLenero** [sgraham785/flywaydb-cli#2]
It would be nice to have a way to set a specific flyway-cli version since the API is subject to change and always downloading the latest version can break automated CI/CD scripts.

**Comment by sgraham785** [comment]
I am open to suggestion for this and PRs are welcome. 

One approach would be to set the version in a `.flyway` file in the root of the project which the package would look for on install or create with the latest version after install was complete. This could be committed with the project and ensure the same version in a CI pipeline.

I just don't have time to accomplish this at the moment.

**Comment by stephan-king** [comment]
Looks like they just released a flyway beta that breaks integration with older releases of mySql. I was auto-upgraded and my builds are broken.

**Comment by sgraham785** [comment]
@stephan-king what version flyway was installed?

**Comment by sgraham785** [comment]
@juanjoLenero @stephan-king I have added support for a `.flyway` version file in 0.8.0.
