### ISSUE TITLE
Bin folder is empty

### ISSUE THREAD

**Issue by Halynsky** [sgraham785/flywaydb-cli#4]
## Bug report:
Platform: Windows x64
"npm": "6.4.1",
"node": "10.10.0"
### Description:

node_modules\.bin\\..\flywaydb-cli\bin\flyway"' is not recognized as an internal or external command

Bin folder is empty and tmp folder is not deleted after download.
I tried to investigate the flow in the code. And it seems that something went wrong.

![image](https://user-images.githubusercontent.com/8502557/48269707-effa5380-e440-11e8-924c-bc8e8f383137.png)

### UPDATE
The problem is in prepublish script which is platform depended
"prepublish": "rm ./bin/flyway && touch ./bin/flyway"

**Comment by sgraham785** [comment]
prepublish should not have an effect on this as it's only run locally to me when I publish the package. the reason for it that prepublish is to clean out bin/flyway that I may have tested with and an empty file there to write to on install. I will investigate a bit, but I haven't tested on windows and don't have a windows machine to test on

**Comment by sgraham785** [comment]
please delete the package run install and paste any errors that you receive during the install.

**Comment by Halynsky** [comment]
I have made a fork from your master, and maybe I will prepare PR with some fixes for Windows.
Did your ever testes this package on Windows x64?
Because after solving one problem I getting another.

**Comment by Halynsky** [comment]
## Update
`Error: Could not find or load main class org.flywaydb.commandline.Main`

The main problem that I can't solve yet is that flyway.cmd is forming paths not correctly. It takes relative folders address from link location. I have modified cmd script to see in what folders it tries to look for Main class.

ECHO %CP%%INSTALLDIR%\lib\%FLYWAY_EDITION%\*
ECHO %INSTALLDIR%\drivers\*

%JAVA_CMD% %JAVA_ARGS% -cp "%CP%%INSTALLDIR%\lib\%FLYWAY_EDITION%\*;%INSTALLDIR%\drivers\*" org.flywaydb.commandline.Main %*

### Result

...project\node_modules\flywaydb-cli\bin\\lib\community\*
...project\node_modules\flywaydb-cli\bin\\drivers\*

Ass you see it's wrong path

**Comment by Halynsky** [comment]
I have one working solution. It's not very nice for development but it works.
We can copy flyway distributive into bin folder entirely. But then we need to prevent commit files into the bin folder. I tried some interesting solutions like pre-push and pre-commit to solve it, but they did not work correctly for this case.

**Comment by Halynsky** [comment]
Please check out my local pull request
https://github.com/Halynsky/flywaydb-cli/pull/1

It's work on Windows. But I still don't like this solution. I just need a fast fix to use it on my Node server.
Symlink will not work according to flyway.cmd script because of windows relative path strategy depending on link location and not on source file location

By the way. Is it correct to keep dist in VCS?
I don't know about npm requirement for publishing. But in common cases, it's not good practice to keep compiled distributives in the VCS.

**Comment by sgraham785** [comment]
i took a look. what about the solution do you not like? also i think for a solution for bin would be to add a `.gitkeep` then add `/bin` to `.gitignore` but add back just `/bin/.gitkeep`, this should prevent anything from ever being committed there. as far as `dist` i commit cause it's small and removes some wonky publish workflows i didn't want to manage at the time

**Comment by sgraham785** [comment]
this should no longer happen as of 0.8.0 which adds better support for windows as implemented by @Halynsky and modified slightly by myself

**Comment by Halynsky** [comment]
Thank you very much. I have used my Fork for a long time. I will test your update when I will have time.
