### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by indreek** [sgraham785/flywaydb-cli#7]
npm install flywaydb-cli

> flywaydb-cli@0.8.1 install /home/indrek/test/node_modules/flywaydb-cli
> node dist/installer.js

Found version in .flyway ->  5.2.4
Downloading https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz
Saving to /home/indrek/test/node_modules/flywaydb-cli/tmp/flyway-commandline-5.2.4-linux-x64.tar.gz
  [=======================================-] 97%
Received 61.18 MB total.
error --> Error: ENOENT: no such file or directory, stat '/home/indrek/test/node_modules/flywaydb-cli/lib/flyway-5.2.4/jre/lib/amd64/server/libjsig.so'
+ flywaydb-cli@0.8.1
added 4 packages from 2 contributors, updated 1 package and audited 439 packages in 13.336s
found 0 vulnerabilities

Ubuntu 18.01
If i downgrade to 0.5.1 works perfectly.

**Comment by indreek** [comment]
6.0 is the last version that works.

**Comment by aldenquimby** [comment]
This is fixed as of #8, but note that #18 now exists
